apiVersion: batch/v1
kind: Job
metadata:
  name: presync-verify-sbom
  namespace: gitops-demo
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: verify-sbom
          image: ghcr.io/sigstore/cosign/cosign:v2.2.4
          args:
            - "verify-attestation"
            - "--type"
            - "spdx"
            - "--certificate-oidc-issuer"
            - "https://token.actions.githubusercontent.com"
            - "--certificate-identity-regexp"
            - "https://github.com/dev-ahuja/lab1/.*"
            - docker.io/devenderahuja936/gitops-demo-app@sha256:7b8d60c84b44c9b8e3b176e2c40082cb9db7f8424f9a5f0a2ee47a7afa92a69b
          env:
            - name: COSIGN_EXPERIMENTAL
              value: "true"
