apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: gitops-demo
spec:
  selector:
    app: demo-appp
  ports:
    - name: http
      port: 80
      targetPort: 3003
      protocol: TCP
  type: ClusterIP
