apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-secure-demo
  namespace: argocdd
spec:
  project: default
  source:
    repoURL: https://github.com/dev-ahuja/gitopsdemoB
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demoo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
